rails-friend/final/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :friends
  get 'home/about'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

rails-friend/final/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

rails-friend/final/app/models/friend.rb
class Friend < ApplicationRecord
end

rails-friend/final/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

rails-friend/final/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

rails-friend/final/app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter)
    end
end

rails-friend/final/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

rails-friend/final/app/helpers/application_helper.rb
module ApplicationHelper
end

rails-friend/final/app/helpers/friends_helper.rb
module FriendsHelper
end

rails-friend/final/app/helpers/home_helper.rb
module HomeHelper
end

rails-friend/final/app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :first_name, style: "display: block", class:"form-label" %>
    <%= form.text_field :first_name, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :last_name, style: "display: block", class:"form-label" %>
    <%= form.text_field :last_name, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :email, style: "display: block", class:"form-label" %>
    <%= form.text_field :email, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :phone, style: "display: block", class:"form-label" %>
    <%= form.text_field :phone, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :twitter, style: "display: block", class:"form-label" %>
    <%= form.text_field :twitter, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

rails-friend/final/app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">

  <p>
    <strong>First name:</strong>
    <%= friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= friend.twitter %>
  </p>

</div>

rails-friend/final/app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend, class:"btn btn-secondary" %>
  <%= link_to "Back to friends", friends_path, class:"btn btn-dark" %>
</div>

rails-friend/final/app/views/friends/index.html.erb
<h1>Friends</h1>

<% @friends.each do |friend| %>
  <div id="friends" class="card mb-3">
    <div class="card-body">
      <%= render friend %>
      <p>
        <%= link_to "Show this friend", friend, class:"btn btn-light" %>
      </p>
    </div>
  </div>
<% end %>

<%= link_to "New friend", new_friend_path, class:"btn btn-danger mb-4" %>

rails-friend/final/app/views/friends/new.html.erb
<h1>New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path, class:"btn btn-secondary" %>
</div>

rails-friend/final/app/views/friends/show.html.erb
<div id="<%= dom_id @friend %>">
  <div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5">
      <h1 class="display-4"><%= @friend.first_name %> <%= @friend.last_name %></h1>
      <hr class="my-4">
      <p class="col-md-8 fs-4">
        <%= @friend.email %> | <%= @friend.phone %> | <%= @friend.twitter %>
      </p>
      <%= link_to "Edit this friend", edit_friend_path(@friend), class:"btn btn-secondary" %>
      <%= link_to "Back to friends", friends_path , class:"btn btn-dark" %>
    </div>
  </div>
  <p>
    <strong>Email:</strong>
    <%= @friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= @friend.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= @friend.twitter %>
  </p>

</div>


<div>
  <%= button_to "Destroy this friend", @friend, method: :delete, class:"btn btn-danger" %>
</div>

rails-friend/final/app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Final App", root_path, class:"navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class:"nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", home_about_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Friends", friends_path, class:"nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "New Friend", new_friend_path, class:"nav-link" %>
          </li>
        <% end %>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      <ul class="navbar-nav mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Sign out", destroy_user_session_path, method: :delete, class:"nav-link text-primary" %>
          </li>
          <li class="nav-item">
            <%= link_to "Profile", edit_user_registration_path  , class:"nav-link text-secondary" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class:"nav-link text-primary" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign in", new_user_session_path, class:"nav-link text-secondary" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

rails-friend/final/app/views/home/about.html.erb
<h1>About Us ......</h1>

rails-friend/final/app/views/home/index.html.erb
<h1>Hello World</h1>
<p>This is my second rails project</p>

rails-friend/final/app/views/layouts/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

rails-friend/final/app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Final App</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class='container'>
      <br/>
      <% if notice %>
        <%= render 'layouts/alert' %>
      <% end %>
      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>